### ISSUE TITLE
CSScript.Execute doesn't work since 3.16

### ISSUE THREAD

**Issue by robopolomsky** [oleg-shilo/cs-script.net-framework#1]
I have very trivial application based on CS-Script.bin NuGet package. It works with legacy versions 2.16 -> 3.14, but starting from 3.16 it does nothing with no response.

```
using System;
using CSScriptLibrary;

namespace ConsoleApp
{
    class Program
    {
        static void Main()
        {
            CSScript.Execute(PrintScriptErrorMsg, new[] {"c:\\Temp\\Simple.cs" });
        }
        private static void PrintScriptErrorMsg(string message)
        {
            Console.Out.WriteLine(message);
        }
    }
}
```

My Simple.cs is just hello world application:
```
using System;

namespace Simple
{
  class Script
  {
      public static void Main(string[] args)
      {
          Console.Out.WriteLine("Hello");
      }
  }
}
```

2.6 - 3.14:
![2021-08-24 11_01_35-ConsoleApp3_3 14](https://user-images.githubusercontent.com/19485666/130589263-a99a9c8b-46cb-43ae-b8c6-e9196d814bcd.png)

3.16 - 3.30.5.1:
![2021-08-24 11_01_35-ConsoleApp3](https://user-images.githubusercontent.com/19485666/130588926-e6782c01-9297-4206-bf30-e76227a216eb.png)

cscs still works also on new versions. But not the `CSScript.Execute` call. Is there any switch or setting I miss?

**Comment by oleg-shilo** [comment]
It's difficult to comment since you are using quite old version of the product. 
I encourage you to try to move to the latest version and use new API, which was present for a few years side-by-side with the legacy API you are using.

The latest CS-Script nuget package targets .NET 5(Core). But it can also be hosted by .NET Framework hosts thanks to the fact the the assembly is compiled for .NET Standard 2.

```c#
dynamic script = CSScript.Evaluator
                         .LoadMethod(@"public void print()
                                       {
                                           Console.Out.WriteLine(""Hello"");
                                       }");
script.print();
``` 

And with this new API you can choose whatever loading you want: file, code, delegate...

![image](https://user-images.githubusercontent.com/16729806/130627321-eeee9e09-87c8-4c53-9ef5-c77c2eefdcdc.png)

**Comment by robopolomsky** [comment]
Thanks for the answer, @oleg-shilo. I understand now that the "Execute" is the "legacy" API. The thing is that my ~10 years old code is using `Execute` with [/e switch](https://www.cs-script.net/cs-script/help-legacy/Compile.html) to create ".exe" file. I hoped to migrate to the latest CS Script version and extend the functionality, but I found nothing capable of doing that today. `Execute` doesn't work anymore and I see no new API instead of `Execute /e`.

**Comment by oleg-shilo** [comment]
You still can achieve the functionality you were describing in your sample:
```C#
static MethodInfo CSScriptLoad(string script)
    => Assembly
        .LoadFile(CSScript.Evaluator.CompileAssemblyFromFile(script, script + ".dll"))
        .GetTypes()
        .SelectMany(t => t.GetMethods())
        .First(m => m.IsStatic && m.Name == "Main");

. . .

CSScriptLoad(@"D:\test.cs").Invoke(null, new object[] { null });
```

**Comment by robopolomsky** [comment]
That should work, thanks. There is small issue: I can't find `CompileAssemblyFromFile`, but this works:

```
static MethodInfo CSScriptLoad(string script)
    => Assembly
        .LoadFile(CSScript.CompileFile(script, script + ".dll"))
        .GetTypes()
        .SelectMany(t => t.GetMethods())
        .First(m => m.IsStatic && m.Name == "Main");

. . .

CSScriptLoad(@"D:\test.cs").Invoke(null, new object[] { null });
```

**Comment by oleg-shilo** [comment]
:)
> I can't find CompileAssemblyFromFile, 

It is because you are not working with the latest version. You are still using an obsolete release. 
But if you want to keep that version and... it works for you. Then... just keep what works for you.

**Comment by robopolomsky** [comment]
I believe I have the latest one: I got 3.30.5.1 now. It's not there.

**Comment by oleg-shilo** [comment]
The latest version of the product is hosted here https://github.com/oleg-shilo/cs-script
And the version is 
![image](https://user-images.githubusercontent.com/16729806/130789789-565fd82f-571a-49f3-b9a5-8f146c479b5f.png)

This very github project is a repository for CS-Script release that targets an effectively obsolete version of runtime - .NET Framework. And since the runtime vendor MS declared no intention to further develop the framework any further, CS-Script for this framework will not be developed any further neither.

Thus the new features will be delivered via CS-Script edition targeting .NET 5. Hosted on https://github.com/oleg-shilo/cs-script
I encourage you to give it a try. As I mentioned before, you can still use it in .NET Framework applications.

**Comment by robopolomsky** [comment]
I see. I mistakenly included this .net-framework version into my .NET 5.0 sample. It works with CS-Script 4.1. Thanks for all your support.

**Comment by oleg-shilo** [comment]
you are very welcome.
glad to help
